apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-manager-deployment
spec:
  selector:
    matchLabels:
      app: member_manager
  replicas: 1
  template:
    metadata:
      labels:
        app: member_manager
    spec:
      containers:
        - name: myapp
          image: myapp
          ports:
            - containerPort: 8080
              name: api-port
            - containerPort: 5005
              name: debug-port
          env:
            - name: spring.data.mongodb.host
              value: mongo-service
---
apiVersion: v1
kind: Service
metadata:
  name: member-manager-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: api-port
  selector:
    app: member_manager
  type: NodePort