version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  app_container:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mongodb_container:database"

volumes:
  mongodb_data_container:
